### ISSUE TITLE
Adjust queries to changes URL handling of API

### ISSUE THREAD

**Issue by bkonetzny** [janniksam/Kinoheld.Api.Client#9]
The URL handling in the kinoheld API has changed, unused fields got removed to reduce complexity.

1. Properties `absoluteUrl` and `relativeUrl` in the [Url type](https://graph.kinoheld.de/graphql/v1/docs/url.doc.html) are removed in favor of `url`, which is now always an absolute URL.
2. The `url` property of the [Image type](https://graph.kinoheld.de/graphql/v1/docs/image.doc.html) is not an Url type anymore, but a simple string.

**Comment by janniksam** [comment]
Thanks for letting me know, I will implement these changes asap.

**Comment by janniksam** [comment]
Both this API Client and the alexa skill that depends on the api client should be fixed now.
